// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String privateKeyFromSeed({required List<int> seed, dynamic hint}) =>
    RustLib.instance.api.crateApiAleoPrivateKeyFromSeed(seed: seed, hint: hint);

String privateKeyToViewKey({required String privateKey, dynamic hint}) =>
    RustLib.instance.api
        .crateApiAleoPrivateKeyToViewKey(privateKey: privateKey, hint: hint);

String privateKeyToAddress({required String privateKey, dynamic hint}) =>
    RustLib.instance.api
        .crateApiAleoPrivateKeyToAddress(privateKey: privateKey, hint: hint);

String signMessage(
        {required List<int> messageBytes,
        required String privateKey,
        dynamic hint}) =>
    RustLib.instance.api.crateApiAleoSignMessage(
        messageBytes: messageBytes, privateKey: privateKey, hint: hint);

Future<List<String>> generatePublicTransferDelegateData(
        {required String privateKey,
        required double amountCredits,
        required String recipient,
        required double feeCredits,
        dynamic hint}) =>
    RustLib.instance.api.crateApiAleoGeneratePublicTransferDelegateData(
        privateKey: privateKey,
        amountCredits: amountCredits,
        recipient: recipient,
        feeCredits: feeCredits,
        hint: hint);

Future<double> getPublicBalance(
        {required String url,
        required String networkId,
        required String address,
        dynamic hint}) =>
    RustLib.instance.api.crateApiAleoGetPublicBalance(
        url: url, networkId: networkId, address: address, hint: hint);
